/**
 * Vercel Serverless Function: POST /api/contact
 * Handles contact form and demo booking submissions in production on Vercel.
 * Uses Resend transactional email API.
 */

import { Resend } from 'resend';

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const PHONE_RE = /^[\+\d\s\-\(\)]{7,20}$/;

function getIST() {
  return new Date().toLocaleString('en-IN', {
    timeZone: 'Asia/Kolkata',
    dateStyle: 'full',
    timeStyle: 'long',
  });
}

function sanitize(str) {
  if (!str) return '—';
  return String(str).replace(/</g, '&lt;').replace(/>/g, '&gt;').trim();
}

function emailRow(label, value) {
  return `
    <tr>
      <td style="padding:10px 16px;font-weight:600;color:#94a3b8;font-size:13px;white-space:nowrap;vertical-align:top;border-bottom:1px solid #1e293b;">${label}</td>
      <td style="padding:10px 16px;color:#f1f5f9;font-size:14px;border-bottom:1px solid #1e293b;">${value}</td>
    </tr>`;
}

function buildEmailTemplate({ title, accentColor, badge, rows, submittedOn, browser, device, ip }) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1.0" />
  <title>${title}</title>
</head>
<body style="margin:0;padding:0;background:#0a0e1a;font-family:'Segoe UI',Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0a0e1a;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">
          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#0d1220,#111827);border-radius:16px 16px 0 0;padding:36px 40px 28px;border:1px solid #1e293b;border-bottom:none;">
              <div style="display:inline-block;background:${accentColor}18;border:1px solid ${accentColor}44;border-radius:50px;padding:6px 16px;margin-bottom:16px;">
                <span style="color:${accentColor};font-size:11px;font-weight:700;letter-spacing:0.1em;text-transform:uppercase;">${badge}</span>
              </div>
              <h1 style="margin:0;color:#f1f5f9;font-size:22px;font-weight:700;line-height:1.3;">${title}</h1>
              <p style="margin:8px 0 0;color:#64748b;font-size:13px;">Received via Aculion website · ${submittedOn}</p>
            </td>
          </tr>
          <!-- Body -->
          <tr>
            <td style="background:#0d1220;border:1px solid #1e293b;border-top:3px solid ${accentColor};border-bottom:none;padding:0;">
              <table width="100%" cellpadding="0" cellspacing="0">
                ${rows}
              </table>
            </td>
          </tr>
          <!-- Meta info -->
          <tr>
            <td style="background:#080b14;border:1px solid #1e293b;border-top:none;border-bottom:none;padding:0;">
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr><td colspan="2" style="padding:12px 16px 4px;font-size:11px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;color:#475569;">Submission Metadata</td></tr>
                ${emailRow('Browser', browser)}
                ${emailRow('Device', device)}
                ${emailRow('IP Address', ip)}
              </table>
            </td>
          </tr>
          <!-- Footer -->
          <tr>
            <td style="background:#060912;border:1px solid #1e293b;border-top:none;border-radius:0 0 16px 16px;padding:24px 40px;text-align:center;">
              <p style="margin:0;color:#334155;font-size:12px;">This email was automatically generated by the Aculion website form system.</p>
              <p style="margin:8px 0 0;color:#334155;font-size:12px;">© ${new Date().getFullYear()} Aculion · AI-Powered OOH Intelligence</p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}

export default async function handler(req, res) {
  // Set CORS headers for Vercel functions
  const allowedOrigin = process.env.FRONTEND_URL || 'https://www.aculion.com';
  res.setHeader('Access-Control-Allow-Origin', allowedOrigin);
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ success: false, message: 'Method not allowed' });
  }

  try {
    const body = typeof req.body === 'string' ? JSON.parse(req.body) : req.body;
    if (!body || typeof body !== 'object') {
      return res.status(400).json({ success: false, message: 'Invalid request body.' });
    }

    const {
      name, company, email, phone, billboards, message,
      inquiryType, preferredDate, preferredTime, preferredMeetingMode,
      browser, device, ip,
      _honeypot,
    } = body;

    if (_honeypot) {
      return res.status(200).json({ success: true, message: 'Thank you! Your inquiry has been submitted successfully.' });
    }

    if (!name?.trim()) return res.status(400).json({ success: false, message: 'Full name is required.' });
    if (!company?.trim()) return res.status(400).json({ success: false, message: 'Company name is required.' });
    if (!email?.trim() || !EMAIL_RE.test(email)) return res.status(400).json({ success: false, message: 'A valid business email is required.' });
    if (phone?.trim() && !PHONE_RE.test(phone)) return res.status(400).json({ success: false, message: 'Phone number contains invalid characters.' });

    if (message && message.length > 5000) {
      return res.status(400).json({ success: false, message: 'Message is too long (max 5000 characters).' });
    }

    if (inquiryType === 'Book a Demo') {
      if (!preferredDate) return res.status(400).json({ success: false, message: 'Preferred date is required for demo booking.' });
      if (!preferredTime) return res.status(400).json({ success: false, message: 'Preferred time is required for demo booking.' });
      if (!preferredMeetingMode) return res.status(400).json({ success: false, message: 'Preferred meeting mode is required for demo booking.' });
    }

    const resendKey = (process.env.RESEND_API_KEY || '').trim();
    if (!resendKey) {
      console.error('RESEND_API_KEY is not set in environment variables');
      return res.status(500).json({
        success: false,
        message: 'Unable to send your inquiry right now. Please try again later.',
      });
    }

    const resend = new Resend(resendKey);
    const recipient = process.env.RECIPIENT_EMAIL || process.env.CONTACT_EMAIL || 'connect@aculion.com';
    const clientIp = (ip && ip !== 'Unavailable') ? ip : (req.headers['x-forwarded-for'] || req.socket?.remoteAddress || 'Unavailable');
    const submittedOn = getIST();
    const subject = 'New Contact Inquiry - Aculion Website';

    const rows = [
      emailRow('Inquiry Type', sanitize(inquiryType) || 'Contact Sales'),
      emailRow('Full Name', sanitize(name)),
      emailRow('Company Name', sanitize(company)),
      emailRow('Business Email', `<a href="mailto:${sanitize(email)}" style="color:#38bdf8;">${sanitize(email)}</a>`),
      emailRow('Phone Number', sanitize(phone) || '—'),
      emailRow('Number of Billboards', sanitize(billboards) || 'Not specified'),
      inquiryType === 'Book a Demo' ? emailRow('Preferred Demo Date & Time', `${sanitize(preferredDate)} at ${sanitize(preferredTime)}`) : '',
      inquiryType === 'Book a Demo' ? emailRow('Preferred Meeting Mode', sanitize(preferredMeetingMode)) : '',
      emailRow('Message', `<span style="white-space:pre-wrap;">${sanitize(message) || '—'}</span>`),
      emailRow('Submitted On (IST)', submittedOn),
    ].filter(Boolean).join('');

    const html = buildEmailTemplate({
      title: 'New Contact Inquiry - Aculion Website',
      accentColor: '#00f0ff',
      badge: inquiryType || 'Inquiry',
      rows,
      submittedOn,
      browser: sanitize(browser) || 'Unknown',
      device: sanitize(device) || 'Unknown',
      ip: sanitize(clientIp) || 'Unknown',
    });

    const text = `New Contact Inquiry - Aculion Website\n\nInquiry Type: ${inquiryType || 'Contact Sales'}\nFull Name: ${name}\nCompany Name: ${company}\nBusiness Email: ${email}\nPhone Number: ${phone || '—'}\nNumber of Billboards: ${billboards || 'Not specified'}\n${inquiryType === 'Book a Demo' ? `Preferred Demo Date & Time: ${preferredDate} at ${preferredTime}\nPreferred Meeting Mode: ${preferredMeetingMode}\n` : ''}Message:\n${message || '—'}\n\nSubmitted On: ${submittedOn}\nBrowser: ${browser || 'Unknown'}\nDevice: ${device || 'Unknown'}\nIP Address: ${clientIp || 'Unknown'}`;

    const fromAddress = process.env.RESEND_FROM || 'Aculion Website <onboarding@resend.dev>';

    const { data, error } = await resend.emails.send({
      from: fromAddress,
      to: [recipient],
      replyTo: email,
      subject,
      html,
      text,
    });

    if (error) {
      console.error('Resend error:', JSON.stringify(error));
      return res.status(500).json({
        success: false,
        message: 'Unable to send your inquiry right now. Please try again later.',
      });
    }

    return res.status(200).json({
      success: true,
      message: 'Thank you! Your inquiry has been submitted successfully.',
    });

  } catch (err) {
    console.error('Unexpected error in /api/contact:', err?.message || err);
    return res.status(500).json({
      success: false,
      message: 'Unable to send your inquiry right now. Please try again later.',
    });
  }
}
